import { createFileRoute, Link } from '@tanstack/react-router'
import { RefreshCw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { listAdminPosts, updateAdminPost } from '@/lib/admin-repository'

export const Route = createFileRoute('/app/content')({ component: AdminContentPage })

type AdminPost = Awaited<ReturnType<typeof listAdminPosts>>[number]

function AdminContentPage() {
  const [posts, setPosts] = useState<AdminPost[]>([])
  const [status, setStatus] = useState('all')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { setPosts(await listAdminPosts(status === 'all' ? undefined : { status })) } catch (err) { setError(err instanceof Error ? err.message : 'Could not load content.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [status])
  const publish = async (post: AdminPost) => { try { const updated = await updateAdminPost(post.id, { status: post.status === 'published' ? 'draft' : 'published', published: post.status !== 'published' }); setPosts((current) => current.map((item) => item.id === updated?.id ? { ...item, ...updated } : item)) } catch (err) { setError(err instanceof Error ? err.message : 'Could not change the status.') } }
  return <main className="min-h-full bg-muted/20 p-4 md:p-8"><div className="mx-auto max-w-6xl space-y-6"><header className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Administration</p><h1 className="text-2xl font-semibold tracking-tight">Content</h1><p className="mt-1 text-sm text-muted-foreground">Drafts and published posts from creator profiles.</p></div><button type="button" onClick={() => void load()} className="inline-flex h-10 items-center gap-2 rounded-md border bg-background px-3 text-sm"><RefreshCw className="h-4 w-4" />Refresh</button></header>{error && <div className="rounded-md border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}<div className="flex gap-2 overflow-x-auto">{['all','draft','published','scheduled','archived'].map((item) => <button key={item} type="button" onClick={() => setStatus(item)} className={`rounded-full border px-3 py-1.5 text-sm ${status === item ? 'border-primary bg-primary text-primary-foreground' : 'bg-background'}`}>{item === 'all' ? 'All' : item}</button>)}</div><section className="overflow-hidden rounded-xl border bg-background shadow-sm">{loading && <p className="p-8 text-center text-sm text-muted-foreground">Loading content…</p>}{!loading && posts.map((post) => <article key={post.id} className="flex flex-col gap-4 border-b p-4 last:border-b-0 sm:flex-row sm:items-center"><div className="h-20 w-28 shrink-0 overflow-hidden rounded-md bg-muted">{post.type === 'video' ? <video src={post.media_url} poster={post.thumbnail_url ?? undefined} muted className="h-full w-full object-cover" /> : <img src={post.media_url} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate font-medium">{post.title}</p><p className="truncate text-sm text-muted-foreground">{post.caption || 'No caption'}</p><p className="mt-1 text-xs text-muted-foreground">{post.type} · {post.status}</p></div><div className="flex items-center gap-2"><Link to="/creator/$slug" params={{ slug: (post as any).creators?.slug ?? '' }} className="rounded-md px-2 py-1 text-sm text-primary">View profile</Link><button type="button" onClick={() => void publish(post)} className="rounded-md border px-3 py-2 text-sm">{post.status === 'published' ? 'Unpublish' : 'Publish'}</button></div></article>)}{!loading && posts.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">No content in this queue.</p>}</section></div></main>
}
