/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as CreatorSlugRouteImport } from './routes/creator.$slug'
import { Route as AppReelsRouteImport } from './routes/app/reels'
import { Route as AppModelsRouteImport } from './routes/app/models'
import { Route as AppMediaRouteImport } from './routes/app/media'
import { Route as AppFansRouteImport } from './routes/app/fans'
import { Route as AppContentRouteImport } from './routes/app/content'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AppModelsNewRouteImport } from './routes/app/models.new'
import { Route as AppModelsIdRouteImport } from './routes/app/models.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CreatorSlugRoute = CreatorSlugRouteImport.update({
  id: '/creator/$slug',
  path: '/creator/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppFansRoute = AppFansRouteImport.update({
  id: '/fans',
  path: '/fans',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModelsNewRoute = AppModelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppModelsRoute,
} as any)
const AppModelsIdRoute = AppModelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/content': typeof AppContentRoute
  '/app/fans': typeof AppFansRoute
  '/app/media': typeof AppMediaRoute
  '/app/models': typeof AppModelsRouteWithChildren
  '/app/reels': typeof AppReelsRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/models/$id': typeof AppModelsIdRoute
  '/app/models/new': typeof AppModelsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/content': typeof AppContentRoute
  '/app/fans': typeof AppFansRoute
  '/app/media': typeof AppMediaRoute
  '/app/models': typeof AppModelsRouteWithChildren
  '/app/reels': typeof AppReelsRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/app': typeof AppIndexRoute
  '/app/models/$id': typeof AppModelsIdRoute
  '/app/models/new': typeof AppModelsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/content': typeof AppContentRoute
  '/app/fans': typeof AppFansRoute
  '/app/media': typeof AppMediaRoute
  '/app/models': typeof AppModelsRouteWithChildren
  '/app/reels': typeof AppReelsRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/models/$id': typeof AppModelsIdRoute
  '/app/models/new': typeof AppModelsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/terms'
    | '/admin/login'
    | '/app/content'
    | '/app/fans'
    | '/app/media'
    | '/app/models'
    | '/app/reels'
    | '/creator/$slug'
    | '/app/'
    | '/app/models/$id'
    | '/app/models/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/terms'
    | '/admin/login'
    | '/app/content'
    | '/app/fans'
    | '/app/media'
    | '/app/models'
    | '/app/reels'
    | '/creator/$slug'
    | '/app'
    | '/app/models/$id'
    | '/app/models/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/profile'
    | '/reels'
    | '/terms'
    | '/admin/login'
    | '/app/content'
    | '/app/fans'
    | '/app/media'
    | '/app/models'
    | '/app/reels'
    | '/creator/$slug'
    | '/app/'
    | '/app/models/$id'
    | '/app/models/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReelsRoute: typeof ReelsRoute
  TermsRoute: typeof TermsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CreatorSlugRoute: typeof CreatorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/creator/$slug': {
      id: '/creator/$slug'
      path: '/creator/$slug'
      fullPath: '/creator/$slug'
      preLoaderRoute: typeof CreatorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reels': {
      id: '/app/reels'
      path: '/reels'
      fullPath: '/app/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fans': {
      id: '/app/fans'
      path: '/fans'
      fullPath: '/app/fans'
      preLoaderRoute: typeof AppFansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/models/new': {
      id: '/app/models/new'
      path: '/new'
      fullPath: '/app/models/new'
      preLoaderRoute: typeof AppModelsNewRouteImport
      parentRoute: typeof AppModelsRoute
    }
    '/app/models/$id': {
      id: '/app/models/$id'
      path: '/$id'
      fullPath: '/app/models/$id'
      preLoaderRoute: typeof AppModelsIdRouteImport
      parentRoute: typeof AppModelsRoute
    }
  }
}

interface AppModelsRouteChildren {
  AppModelsIdRoute: typeof AppModelsIdRoute
  AppModelsNewRoute: typeof AppModelsNewRoute
}

const AppModelsRouteChildren: AppModelsRouteChildren = {
  AppModelsIdRoute: AppModelsIdRoute,
  AppModelsNewRoute: AppModelsNewRoute,
}

const AppModelsRouteWithChildren = AppModelsRoute._addFileChildren(
  AppModelsRouteChildren,
)

interface AppRouteChildren {
  AppContentRoute: typeof AppContentRoute
  AppFansRoute: typeof AppFansRoute
  AppMediaRoute: typeof AppMediaRoute
  AppModelsRoute: typeof AppModelsRouteWithChildren
  AppReelsRoute: typeof AppReelsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContentRoute: AppContentRoute,
  AppFansRoute: AppFansRoute,
  AppMediaRoute: AppMediaRoute,
  AppModelsRoute: AppModelsRouteWithChildren,
  AppReelsRoute: AppReelsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReelsRoute: ReelsRoute,
  TermsRoute: TermsRoute,
  AdminLoginRoute: AdminLoginRoute,
  CreatorSlugRoute: CreatorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
