-- Internal CRM event foundation.
-- This migration stores only events generated by the application; it does not fabricate external financial history.

create table if not exists public.crm_fan_events (
  id uuid primary key default gen_random_uuid(),
  telegram_id bigint references public.telegram_users (telegram_id) on delete set null,
  creator_id uuid references public.creators (id) on delete set null,
  post_id uuid references public.creator_posts (id) on delete set null,
  event_type text not null check (event_type in (
    'profile_view',
    'post_view',
    'like',
    'comment',
    'follow',
    'paid_unlock',
    'subscription_started',
    'subscription_renewed',
    'subscription_cancelled',
    'tip',
    'custom_order',
    'campaign_click',
    'campaign_conversion'
  )),
  amount numeric(12,2),
  currency text not null default 'Coins',
  idempotency_key text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint crm_fan_events_idempotency_key_unique unique (idempotency_key)
);

create index if not exists crm_fan_events_telegram_occurred_idx
  on public.crm_fan_events (telegram_id, occurred_at desc);
create index if not exists crm_fan_events_creator_occurred_idx
  on public.crm_fan_events (creator_id, occurred_at desc);
create index if not exists crm_fan_events_type_occurred_idx
  on public.crm_fan_events (event_type, occurred_at desc);

create table if not exists public.crm_fan_transactions (
  id uuid primary key default gen_random_uuid(),
  telegram_id bigint references public.telegram_users (telegram_id) on delete set null,
  creator_id uuid references public.creators (id) on delete set null,
  post_id uuid references public.creator_posts (id) on delete set null,
  transaction_type text not null check (transaction_type in (
    'subscription',
    'subscription_renewal',
    'paid_unlock',
    'tip',
    'custom_order',
    'refund'
  )),
  gross_amount numeric(12,2) not null check (gross_amount >= 0),
  agency_amount numeric(12,2) not null default 0 check (agency_amount >= 0),
  creator_amount numeric(12,2) not null default 0 check (creator_amount >= 0),
  operating_cost numeric(12,2) not null default 0 check (operating_cost >= 0),
  currency text not null default 'Coins',
  external_reference text,
  idempotency_key text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint crm_fan_transactions_idempotency_key_unique unique (idempotency_key)
);

create index if not exists crm_fan_transactions_telegram_occurred_idx
  on public.crm_fan_transactions (telegram_id, occurred_at desc);
create index if not exists crm_fan_transactions_creator_occurred_idx
  on public.crm_fan_transactions (creator_id, occurred_at desc);

create table if not exists public.crm_commission_rules (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid references public.creators (id) on delete cascade,
  agency_percent numeric(5,2) not null default 0 check (agency_percent between 0 and 100),
  creator_percent numeric(5,2) not null default 100 check (creator_percent between 0 and 100),
  operating_cost_percent numeric(5,2) not null default 0 check (operating_cost_percent between 0 and 100),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_commission_rules_percent_sum_check check (agency_percent + creator_percent + operating_cost_percent <= 100)
);

create unique index if not exists crm_commission_rules_active_creator_idx
  on public.crm_commission_rules (creator_id)
  where active;

create table if not exists public.crm_campaigns (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid references public.creators (id) on delete cascade,
  name text not null,
  channel text not null check (channel in ('twitter', 'tiktok', 'reddit', 'instagram', 'telegram', 'other')),
  status text not null default 'draft' check (status in ('draft', 'active', 'paused', 'completed', 'archived')),
  budget numeric(12,2) not null default 0 check (budget >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crm_tracking_links (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid references public.crm_campaigns (id) on delete cascade,
  creator_id uuid references public.creators (id) on delete cascade,
  code text not null unique,
  destination_path text not null,
  clicks integer not null default 0 check (clicks >= 0),
  conversions integer not null default 0 check (conversions >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.crm_scheduled_content (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid not null references public.creators (id) on delete cascade,
  post_id uuid references public.creator_posts (id) on delete set null,
  content_type text not null check (content_type in ('feed', 'reels', 'goal', 'poll')),
  status text not null default 'scheduled' check (status in ('draft', 'scheduled', 'published', 'cancelled', 'failed')),
  scheduled_for timestamptz not null,
  payload jsonb not null default '{}'::jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_scheduled_content_due_idx
  on public.crm_scheduled_content (status, scheduled_for);

create table if not exists public.crm_vault_tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  category text not null check (category in ('theme', 'clothing', 'format', 'collaboration', 'nudity_level', 'custom')),
  created_at timestamptz not null default now()
);

create table if not exists public.crm_media_tags (
  media_asset_id uuid not null references public.media_assets (id) on delete cascade,
  tag_id uuid not null references public.crm_vault_tags (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (media_asset_id, tag_id)
);

create table if not exists public.crm_media_events (
  id uuid primary key default gen_random_uuid(),
  media_asset_id uuid references public.media_assets (id) on delete set null,
  telegram_id bigint references public.telegram_users (telegram_id) on delete set null,
  creator_id uuid references public.creators (id) on delete set null,
  event_type text not null check (event_type in ('impression', 'open', 'unlock', 'purchase', 'share')),
  campaign_id uuid references public.crm_campaigns (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists crm_media_events_asset_occurred_idx
  on public.crm_media_events (media_asset_id, occurred_at desc);
create index if not exists crm_media_events_fan_asset_idx
  on public.crm_media_events (telegram_id, media_asset_id);

-- Keep these operational tables private. Admin access can be exposed through authenticated
-- admin procedures once the temporary development bypass is removed.

alter table public.crm_fan_events enable row level security;
alter table public.crm_fan_transactions enable row level security;
alter table public.crm_commission_rules enable row level security;
alter table public.crm_campaigns enable row level security;
alter table public.crm_tracking_links enable row level security;
alter table public.crm_scheduled_content enable row level security;
alter table public.crm_vault_tags enable row level security;
alter table public.crm_media_tags enable row level security;
alter table public.crm_media_events enable row level security;

create policy crm_fan_events_admin_all on public.crm_fan_events for all to public using (is_admin()) with check (is_admin());
create policy crm_fan_transactions_admin_all on public.crm_fan_transactions for all to public using (is_admin()) with check (is_admin());
create policy crm_commission_rules_admin_all on public.crm_commission_rules for all to public using (is_admin()) with check (is_admin());
create policy crm_campaigns_admin_all on public.crm_campaigns for all to public using (is_admin()) with check (is_admin());
create policy crm_tracking_links_admin_all on public.crm_tracking_links for all to public using (is_admin()) with check (is_admin());
create policy crm_scheduled_content_admin_all on public.crm_scheduled_content for all to public using (is_admin()) with check (is_admin());
create policy crm_vault_tags_admin_all on public.crm_vault_tags for all to public using (is_admin()) with check (is_admin());
create policy crm_media_tags_admin_all on public.crm_media_tags for all to public using (is_admin()) with check (is_admin());
create policy crm_media_events_admin_all on public.crm_media_events for all to public using (is_admin()) with check (is_admin());

comment on table public.crm_fan_events is 'Internal first-party events generated by the application; no external transaction history is implied.';
comment on table public.crm_fan_transactions is 'Internal financial events recorded by application flows.';
